# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2ea1a562033948d3db3b4e74b48b6cf03cfc7b777385d495d71fe24056fa7fd0874dc381bffd72aec37aa19b45c823747d5fa3586e45806cf128464c0701aea

test:
  secret_key_base: 8f19b51494281d1e0c9cd11526bfa0deefd139ffd793bfef7b5381892ce63c3418e7eb42b7f31bcfee60435b9e2117e15a72455a16b75d358b2e24050ef9f768

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
